default:
	ln -s ../inits/core/init-evil.el 00_evil.el
	ln -s ../inits/core/init-auto-complete.el 01_auto-complete.el
	ln -s ../inits/core/init-guide-key.el 01_guide-key.el
	ln -s ../inits/core/init-projectile.el 01_projectile.el
	ln -s ../inits/core/init-helm.el 10_helm.el
	ln -s ../inits/core/init-helm-gtags.el 11_helm_gtags.el
	ln -s ../inits/git/init-magit.el 20_magit.el
	ln -s ../inits/editor/init-anzu.el 30_anzu.el
	ln -s ../inits/editor/init-undo-tree.el 30_undo-tree.el
	ln -s ../inits/editor/init-yasnippet.el 30_yasnippet.el
	ln -s ../inits/plugins/init-dired.el 40_dired.el
	ln -s ../inits/plugins/init-emacs-aoj.el 40_emacs-aoj.el
	ln -s ../inits/plugins/init-eww.el 40_eww.el
	ln -s ../inits/plugins/init-org.el 40_org.el
	ln -s ../inits/plugins/init-hatena-blog.el 40_hatena-blog.el
	ln -s ../inits/language/init-c++-mode.el 50_c++-mode.el
	ln -s ../inits/language/init-geiser.el 50_geiser.el
	ln -s ../inits/language/init-haskell-mode.el 50_haskell-mode.el
	ln -s ../inits/language/init-irony.el 50_irony.el
	ln -s ../inits/language/init-js2-mode.el 50_js2-mode.el
	ln -s ../inits/language/init-web-mode.el 50_web-mode.el
	ln -s ../inits/face/init-hl-todo.el 70_hl-todo.el
	ln -s ../inits/face/init-powerline.el 70_powerline.el
	ln -s ../inits/face/init-pretty-symbol.el 70_pretty-symbol.el
	ln -s ../inits/face/init-volatile-highlights.el 70_volatile-highlights.el
	ln -s ../inits/face/init-whitespace.el 70_whitespace.el
	ln -s ../inits/init-keybindings.el 90_keybindings.el
	ln -s ../inits/environment/init-osx.el 90_osx.el

clean:
	rm -rf *.el
	rm -rf *.elc
